var res = {
	sampleLog : "res/samplelog",
    BackGround01_jpg: "res/background_01.jpg",
    BackGround02_jpg: "res/background_02.jpg",
    life1_png: "res/life1.png",
    life2_png: "res/life2.png",
    Menu1_png: "res/Menu1.png",
    Menu2_png: "res/Menu2.png",
    Menu3_png: "res/Menu3.png",
    Menu4_png: "res/Menu4.png",
    Menu5_png: "res/Menu5.png",
    chara1F_png: "res/poti1front.png",
    chara1L_png: "res/poti1left.png",
    chara1R_png: "res/poti1right.png",
    chara1B_png: "res/poti1back.png",
    chara2F_png: "res/poti2front.png",
    chara2L_png: "res/poti2left.png",
    chara2R_png: "res/poti2right.png",
    chara2B_png: "res/poti2back.png",
    chara3F_png: "res/tama3front.png",
    chara3L_png: "res/tama3left.png",
    chara3R_png: "res/tama3right.png",
    chara3B_png: "res/tama3back.png",  
    chara4F_png: "res/tama4front.png",
    chara4L_png: "res/tama4left.png",
    chara4R_png: "res/tama4right.png",
    chara4B_png: "res/tama4back.png",  
    botton1_png: "res/botton1.png",
    botton2_png: "res/botton2.png",
    botton3_png: "res/botton3.png",
    botton4_png: "res/botton4.png",    
    block1_png: "res/blockblue.png",
    block2_png: "res/blockred.png",
    block3_png: "res/blockgreen.png",
    block4_png: "res/blockbrown.png",
    block5_png: "res/blockorange.png",
    block6_png: "res/blockpurple.png",
    block7_png: "res/blockyellow.png",
    fast1_png: "res/fast1.png",
    slow1_png: "res/slow1.png",
    normal1_png: "res/normal1.png",
    fast2_png: "res/fast2.png",
    slow2_png: "res/slow2.png",
    normal2_png: "res/normal2.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}